### ISSUE TITLE
Full course

### ISSUE THREAD

**Issue by shubhamsrivast4u** [sdnr/DLACOM-notebooks#1]
Dear Sir/ Ma'am,
I looked through the index of this course. The index looks great. It will be very helpful if I can access the PDFs or video tutorials of this course. It will save a lot of time. Can you please advise how to access this course?
Thanks

**Comment by sdnr** [comment]
Hi,

Thank you for your interest in our material.
This is part of a lecture at the University of Stuttgart in Germany.
You need to be enrolled as a student to be able to join the course.

Regards,
Sebastian Dörner
